// <auto-generated />
using System;
using GmailOrganiser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GmailOrganiser.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002200123_M3_AutoArchiveSendFailures")]
    partial class M3_AutoArchiveSendFailures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmailOrganiser.Analysis.AnalysisRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttachmentsConverted")
                        .HasColumnType("integer")
                        .HasColumnName("attachments_converted");

                    b.Property<int>("AttachmentsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("attachments_skipped");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("FailedMessages")
                        .HasColumnType("integer")
                        .HasColumnName("failed_messages");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GroupingMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grouping_mode");

                    b.Property<int>("Groups")
                        .HasColumnType("integer")
                        .HasColumnName("groups");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LlmCalls")
                        .HasColumnType("integer")
                        .HasColumnName("llm_calls");

                    b.PrimitiveCollection<string[]>("MessageIds")
                        .HasColumnType("text[]")
                        .HasColumnName("message_ids");

                    b.Property<int>("MessagesCovered")
                        .HasColumnType("integer")
                        .HasColumnName("messages_covered");

                    b.Property<int>("MessagesDerived")
                        .HasColumnType("integer")
                        .HasColumnName("messages_derived");

                    b.Property<int>("MessagesFromMemory")
                        .HasColumnType("integer")
                        .HasColumnName("messages_from_memory");

                    b.Property<int>("MessagesLlm")
                        .HasColumnType("integer")
                        .HasColumnName("messages_llm");

                    b.Property<int>("MixedGroups")
                        .HasColumnType("integer")
                        .HasColumnName("mixed_groups");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer")
                        .HasColumnName("requested_count");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SenderAddress")
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<int>("SkippedMessages")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_messages");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_analysis_runs");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_analysis_runs_status_created_at");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Analysis.SuggestionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<bool>("Edited")
                        .HasColumnType("boolean")
                        .HasColumnName("edited");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_criteria");

                    b.Property<string>("GroupKey")
                        .HasColumnType("text")
                        .HasColumnName("group_key");

                    b.Property<bool>("IsNewLabel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_label");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<bool>("NeedsAction")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_action");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("to_be_deleted");

                    b.Property<string>("TopicLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_label");

                    b.Property<bool>("UnsubscribeSuggested")
                        .HasColumnType("boolean")
                        .HasColumnName("unsubscribe_suggested");

                    b.HasKey("Id")
                        .HasName("pk_suggestions");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_suggestions_message_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_suggestions_run_id");

                    b.HasIndex("SenderAddress", "Status")
                        .HasDatabaseName("ix_suggestions_sender_address_status");

                    b.HasIndex("Status", "Confidence")
                        .HasDatabaseName("ix_suggestions_status_confidence");

                    b.ToTable("suggestions", null, t =>
                        {
                            t.HasCheckConstraint("ck_suggestions_confidence", "confidence BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Fetch.FetchRunMessageRow", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.HasKey("MessageId")
                        .HasName("pk_fetch_run_messages");

                    b.ToTable("fetch_run_messages", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Fetch.FetchStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AccountEmail")
                        .HasColumnType("text")
                        .HasColumnName("account_email");

                    b.Property<int>("AllMailFetched")
                        .HasColumnType("integer")
                        .HasColumnName("all_mail_fetched");

                    b.Property<long?>("AllMailTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("all_mail_total");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("InboxFetched")
                        .HasColumnType("integer")
                        .HasColumnName("inbox_fetched");

                    b.Property<long?>("InboxTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("inbox_total");

                    b.Property<string>("LastHistoryId")
                        .HasColumnType("text")
                        .HasColumnName("last_history_id");

                    b.Property<string>("MailboxPhase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mailbox_phase");

                    b.Property<long?>("MessagesTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("messages_total");

                    b.Property<string>("PageToken")
                        .HasColumnType("text")
                        .HasColumnName("page_token");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fetch_state");

                    b.ToTable("fetch_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_fetch_state_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllMailFetched = 0,
                            InboxFetched = 0,
                            MailboxPhase = "not_started",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Fetch.MessageRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("not_analysed")
                        .HasColumnName("analysis_status");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<bool>("DeletedInGmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted_in_gmail");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasColumnType("text")
                        .HasColumnName("from_name");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_attachment");

                    b.Property<string>("HistoryId")
                        .HasColumnType("text")
                        .HasColumnName("history_id");

                    b.Property<DateTimeOffset>("InternalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("internal_date");

                    b.PrimitiveCollection<string[]>("LabelIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("label_ids");

                    b.Property<string>("ListId")
                        .HasColumnType("text")
                        .HasColumnName("list_id");

                    b.Property<string>("ListUnsubscribe")
                        .HasColumnType("text")
                        .HasColumnName("list_unsubscribe");

                    b.Property<int>("SizeEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("size_estimate");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thread_id");

                    b.Property<string>("ToHeader")
                        .HasColumnType("text")
                        .HasColumnName("to_header");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("AnalysisStatus")
                        .HasDatabaseName("ix_messages_analysis_status");

                    b.HasIndex("InternalDate")
                        .HasDatabaseName("ix_messages_internal_date");

                    b.HasIndex("LabelIds")
                        .HasDatabaseName("ix_messages_label_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LabelIds"), "gin");

                    b.HasIndex("FromAddress", "InternalDate")
                        .HasDatabaseName("ix_messages_from_address_internal_date");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Gmail.OAuthTokenRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_email");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<bool>("ReauthRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("reauth_required");

                    b.Property<string>("RefreshTokenProtected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_protected");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oauth_tokens");

                    b.ToTable("oauth_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_oauth_tokens_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Jobs.JobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cursor")
                        .HasColumnType("jsonb")
                        .HasColumnName("cursor");

                    b.Property<string>("DedupKey")
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("PauseRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pause_requested");

                    b.Property<string>("Progress")
                        .HasColumnType("jsonb")
                        .HasColumnName("progress");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Type", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_type_dedup_key_active")
                        .HasFilter("status IN ('queued', 'running', 'paused')");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Type", "DedupKey"), false);

                    b.HasIndex("Queue", "Status", "CreatedAt")
                        .HasDatabaseName("ix_jobs_queue_status_created_at");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Memory.DecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Edited")
                        .HasColumnType("boolean")
                        .HasColumnName("edited");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<string>("ListId")
                        .HasColumnType("text")
                        .HasColumnName("list_id");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<bool>("NeedsAction")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_action");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ScopeKey")
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SubjectTemplate")
                        .HasColumnType("text")
                        .HasColumnName("subject_template");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("to_be_deleted");

                    b.Property<string>("TopicLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_label");

                    b.HasKey("Id")
                        .HasName("pk_decisions");

                    b.HasIndex("EmbeddingModel", "SenderAddress")
                        .HasDatabaseName("ix_decisions_embedding_model_sender_address");

                    b.HasIndex("ListId", "CreatedAt")
                        .HasDatabaseName("ix_decisions_list_id_created_at");

                    b.HasIndex("ScopeKey", "CreatedAt")
                        .HasDatabaseName("ix_decisions_scope_key_created_at");

                    b.HasIndex("SenderAddress", "Outcome", "CreatedAt")
                        .HasDatabaseName("ix_decisions_sender_address_outcome_created_at");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Review.ActionBatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("CreatedLabelIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("created_label_ids")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<int>("SendFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("send_failures");

                    b.Property<Guid?>("UndoOf")
                        .HasColumnType("uuid")
                        .HasColumnName("undo_of");

                    b.Property<DateTimeOffset?>("UndoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("undone_at");

                    b.HasKey("Id")
                        .HasName("pk_action_batches");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_action_batches_created_at");

                    b.ToTable("action_batches", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Review.ActionLogRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("LabelIdsAfter")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("label_ids_after");

                    b.PrimitiveCollection<string[]>("LabelIdsBefore")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("label_ids_before");

                    b.PrimitiveCollection<string[]>("LabelsAdded")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels_added");

                    b.PrimitiveCollection<string[]>("LabelsRemoved")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels_removed");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.Property<Guid?>("UndoneByBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("undone_by_batch_id");

                    b.HasKey("Id")
                        .HasName("pk_action_log");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_action_log_batch_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_action_log_message_id");

                    b.ToTable("action_log", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Senders.SenderRow", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("Allowlisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allowlisted");

                    b.Property<int>("AnalysedCount")
                        .HasColumnType("integer")
                        .HasColumnName("analysed_count");

                    b.Property<int>("AppliedCount")
                        .HasColumnType("integer")
                        .HasColumnName("applied_count");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Address")
                        .HasName("pk_senders");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_senders_domain");

                    b.ToTable("senders", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Settings.SettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Analysis.SuggestionRow", b =>
                {
                    b.HasOne("GmailOrganiser.Fetch.MessageRow", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestions_messages_message_id");

                    b.HasOne("GmailOrganiser.Analysis.AnalysisRunRow", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_suggestions_analysis_runs_run_id");
                });

            modelBuilder.Entity("GmailOrganiser.Review.ActionLogRow", b =>
                {
                    b.HasOne("GmailOrganiser.Review.ActionBatchRow", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_action_log_action_batches_batch_id");
                });
#pragma warning restore 612, 618
        }
    }
}
