// <auto-generated />
using System;
using GmailOrganiser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GmailOrganiser.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002083221_M2_JobVersion")]
    partial class M2_JobVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GmailOrganiser.Fetch.FetchStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AccountEmail")
                        .HasColumnType("text")
                        .HasColumnName("account_email");

                    b.Property<int>("AllMailFetched")
                        .HasColumnType("integer")
                        .HasColumnName("all_mail_fetched");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("InboxFetched")
                        .HasColumnType("integer")
                        .HasColumnName("inbox_fetched");

                    b.Property<string>("LastHistoryId")
                        .HasColumnType("text")
                        .HasColumnName("last_history_id");

                    b.Property<string>("MailboxPhase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mailbox_phase");

                    b.Property<long?>("MessagesTotal")
                        .HasColumnType("bigint")
                        .HasColumnName("messages_total");

                    b.Property<string>("PageToken")
                        .HasColumnType("text")
                        .HasColumnName("page_token");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fetch_state");

                    b.ToTable("fetch_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_fetch_state_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllMailFetched = 0,
                            InboxFetched = 0,
                            MailboxPhase = "not_started",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Fetch.MessageRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("not_analysed")
                        .HasColumnName("analysis_status");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<bool>("DeletedInGmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted_in_gmail");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasColumnType("text")
                        .HasColumnName("from_name");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_attachment");

                    b.Property<string>("HistoryId")
                        .HasColumnType("text")
                        .HasColumnName("history_id");

                    b.Property<DateTimeOffset>("InternalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("internal_date");

                    b.PrimitiveCollection<string[]>("LabelIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("label_ids");

                    b.Property<string>("ListId")
                        .HasColumnType("text")
                        .HasColumnName("list_id");

                    b.Property<string>("ListUnsubscribe")
                        .HasColumnType("text")
                        .HasColumnName("list_unsubscribe");

                    b.Property<int>("SizeEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("size_estimate");

                    b.Property<string>("Snippet")
                        .HasColumnType("text")
                        .HasColumnName("snippet");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thread_id");

                    b.Property<string>("ToHeader")
                        .HasColumnType("text")
                        .HasColumnName("to_header");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("AnalysisStatus")
                        .HasDatabaseName("ix_messages_analysis_status");

                    b.HasIndex("FromAddress")
                        .HasDatabaseName("ix_messages_from_address");

                    b.HasIndex("InternalDate")
                        .HasDatabaseName("ix_messages_internal_date");

                    b.HasIndex("LabelIds")
                        .HasDatabaseName("ix_messages_label_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LabelIds"), "gin");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Gmail.OAuthTokenRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_email");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<bool>("ReauthRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("reauth_required");

                    b.Property<string>("RefreshTokenProtected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_protected");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oauth_tokens");

                    b.ToTable("oauth_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_oauth_tokens_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("GmailOrganiser.Jobs.JobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancel_requested");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cursor")
                        .HasColumnType("jsonb")
                        .HasColumnName("cursor");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("PauseRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pause_requested");

                    b.Property<string>("Progress")
                        .HasColumnType("jsonb")
                        .HasColumnName("progress");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_type_active")
                        .HasFilter("status IN ('queued', 'running', 'paused')");

                    b.HasIndex("Queue", "Status", "CreatedAt")
                        .HasDatabaseName("ix_jobs_queue_status_created_at");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Senders.SenderRow", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("Allowlisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allowlisted");

                    b.Property<int>("AnalysedCount")
                        .HasColumnType("integer")
                        .HasColumnName("analysed_count");

                    b.Property<int>("AppliedCount")
                        .HasColumnType("integer")
                        .HasColumnName("applied_count");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Address")
                        .HasName("pk_senders");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_senders_domain");

                    b.ToTable("senders", (string)null);
                });

            modelBuilder.Entity("GmailOrganiser.Settings.SettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_singleton", "id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
